// Generated by node scripts/build-prices.mjs. Do not edit this copy.
import Stripe from "npm:stripe@22.6.2";
import { createClient } from "npm:@supabase/supabase-js@2.117.2";
import { corsHeaders } from "npm:@supabase/supabase-js@2.117.2/cors";
const priceCatalog = {
  "shipping_cents": 0,
  "products": {
    "1": {
      "name": "2 Euros Barbara of Celje",
      "price_cents": 100
    },
    "2": {
      "name": "2 Euros Sipsik",
      "price_cents": 1499
    },
    "3": {
      "name": "2 Euros University of Ljubljana",
      "price_cents": 1499
    },
    "4": {
      "name": "2 Euros Italian National Police",
      "price_cents": 1499
    },
    "5": {
      "name": "2 Euros Academy of Athens",
      "price_cents": 1499
    },
    "7": {
      "name": "2 Euros Maria Callas",
      "price_cents": 1499
    },
    "8": {
      "name": "2 Euro Rotary",
      "price_cents": 1499
    },
    "9": {
      "name": "2 Euros First Flight from Malta",
      "price_cents": 1499
    },
    "10": {
      "name": "2 Euros Presidency European Union",
      "price_cents": 1499
    },
    "11": {
      "name": "2 Euros Basketball in Lithuania",
      "price_cents": 1499
    },
    "12": {
      "name": "2 Euros Belgian Presidency of the Council of the EU",
      "price_cents": 1499
    },
    "13": {
      "name": "2 Euros Primož Trubar",
      "price_cents": 1499
    },
    "14": {
      "name": "2 Euros Adam Bohorič",
      "price_cents": 1499
    },
    "15": {
      "name": "2 Euros Ljubljana Botanical Garden",
      "price_cents": 1499
    },
    "16": {
      "name": "2 Euros Energy Independence",
      "price_cents": 1499
    },
    "17": {
      "name": "2 Euros Glory to Ukraine",
      "price_cents": 1499
    },
    "18": {
      "name": "2 Euros Guimarães",
      "price_cents": 1499
    },
    "19": {
      "name": "2 Euros Ivan Cankar",
      "price_cents": 1499
    },
    "20": {
      "name": "2 Euros Provincial Museum for Carniola",
      "price_cents": 1499
    },
    "21": {
      "name": "2 Euros Erasmus Slovenia",
      "price_cents": 1499
    },
    "22": {
      "name": "2 Euros Marine Nationale 400ans",
      "price_cents": 1499
    },
    "23": {
      "name": "2 Euros Visegrad Group",
      "price_cents": 1499
    },
    "24": {
      "name": "2 Euros Centaurea Cyanus",
      "price_cents": 1499
    },
    "25": {
      "name": "2 Euros Raamat 500",
      "price_cents": 1499
    },
    "26": {
      "name": "2 Euros 730 years of the University of Coimbra",
      "price_cents": 1499
    },
    "27": {
      "name": "2 Euros Bundesländer II - Bremen",
      "price_cents": 1499
    },
    "28": {
      "name": "2 Euros Constantin Caratheodory",
      "price_cents": 1499
    }
  }
};

type Product = { name: string; price_cents: number };
const PRODUCTS: Record<string, Product> = priceCatalog.products;
const SHIPPING_CENTS = priceCatalog.shipping_cents;

type Dependencies = {
  env: (name: string) => string | undefined;
  createSupabaseClient: typeof createClient;
  createStripeClient: (secret: string) => Pick<Stripe, "checkout">;
};

function jsonResponse(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function getSupabasePublicKey(env: Dependencies["env"]): string | null {
  const legacyKey = env("SUPABASE_ANON_KEY");
  if (legacyKey) return legacyKey;
  const publishableKeys = env("SUPABASE_PUBLISHABLE_KEYS");
  if (!publishableKeys) return null;
  try {
    const parsed = JSON.parse(publishableKeys);
    const key = parsed.default || Object.values(parsed)[0];
    return typeof key === "string" && key ? key : null;
  } catch { return null; }
}

export function createCheckoutHandler(deps: Dependencies) {
  return async (req: Request): Promise<Response> => {
    if (req.method === "OPTIONS") {
      return new Response("ok", { status: 200, headers: corsHeaders });
    }
    if (req.method !== "POST") return jsonResponse({ error: "Method not allowed" }, 405);
    try {
      const authHeader = req.headers.get("Authorization");
      if (!authHeader) return jsonResponse({ error: "You must be logged in" }, 401);
      const stripeSecret = deps.env("STRIPE_SECRET_KEY");
      const supabaseUrl = deps.env("SUPABASE_URL");
      const supabaseKey = getSupabasePublicKey(deps.env);
      if (!stripeSecret) return jsonResponse({ error: "Stripe secret key is missing" }, 500);
      if (!supabaseUrl || !supabaseKey) return jsonResponse({ error: "Supabase configuration is missing" }, 500);
      const supabase = deps.createSupabaseClient(supabaseUrl, supabaseKey, {
        global: { headers: { Authorization: authHeader } },
        auth: { persistSession: false, autoRefreshToken: false },
      });
      const { data: { user }, error: userError } = await supabase.auth.getUser();
      if (userError || !user) return jsonResponse({ error: "Invalid user session" }, 401);
      const { data: cart, error: cartError } = await supabase.from("cart")
        .select("coin_id, quantity").eq("user_id", user.id);
      if (cartError) return jsonResponse({ error: "Could not load cart" }, 500);
      if (!cart?.length) return jsonResponse({ error: "Your cart is empty" }, 400);
      const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] = [];
      for (const item of cart) {
        const coinId = Number(item.coin_id);
        const quantity = Number(item.quantity);
        if (!Number.isSafeInteger(coinId) || coinId < 1) return jsonResponse({ error: "Invalid coin ID" }, 400);
        const product = PRODUCTS[coinId];
        if (!product) return jsonResponse({ error: `Unknown coin ID: ${coinId}` }, 400);
        if (!Number.isSafeInteger(quantity) || quantity < 1 || quantity > 100) {
          return jsonResponse({ error: `Invalid quantity for coin ${coinId}` }, 400);
        }
        if (!Number.isSafeInteger(product.price_cents) || product.price_cents < 0) {
          throw new Error(`Invalid price configuration for coin ${coinId}`);
        }
        // Always use the server's catalogue; request-body prices are ignored.
        lineItems.push({ quantity, price_data: {
          currency: "eur", unit_amount: product.price_cents,
          product_data: { name: product.name },
        } });
      }
      if (!Number.isSafeInteger(SHIPPING_CENTS) || SHIPPING_CENTS < 0) {
        throw new Error("Invalid shipping price configuration");
      }
      const stripe = deps.createStripeClient(stripeSecret);
      const session = await stripe.checkout.sessions.create({
        mode: "payment", line_items: lineItems,
        shipping_address_collection: { allowed_countries: [
          "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU",
          "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE",
        ] },
        shipping_options: [{ shipping_rate_data: {
          type: "fixed_amount", fixed_amount: { amount: SHIPPING_CENTS, currency: "eur" },
          display_name: "EU Shipping",
        } }],
        phone_number_collection: { enabled: true },
        customer_email: user.email ?? undefined,
        client_reference_id: user.id, metadata: { user_id: user.id },
        success_url: "https://arkianscollectibles.com/success.html?session_id={CHECKOUT_SESSION_ID}",
        cancel_url: "https://arkianscollectibles.com/cart.html",
      });
      if (!session.url) return jsonResponse({ error: "Stripe checkout URL was not returned" }, 500);
      return jsonResponse({ url: session.url });
    } catch (error) {
      console.error("Checkout error:", error);
      return jsonResponse({ error: "Checkout failed" }, 500);
    }
  };
}

Deno.serve(createCheckoutHandler({
  env: (name) => Deno.env.get(name),
  createSupabaseClient: createClient,
  createStripeClient: (secret) => new Stripe(secret),
}));
