// Generated by node scripts/build-prices.mjs. Do not edit this copy.
import Stripe from "npm:stripe@22.6.2";
import { createClient } from "npm:@supabase/supabase-js@2.117.2";
import { corsHeaders } from "npm:@supabase/supabase-js@2.117.2/cors";
const priceCatalog = {
  "shipping_cents": 300,
  "products": {
    "1": {
      "name": "2 Euros Barbara of Celje",
      "price_cents": 1499,
      "country": "Slovenia",
      "year": 2014,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/001.jpg"
    },
    "2": {
      "name": "2 Euros Sipsik",
      "price_cents": 1499,
      "country": "Estonia",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/002.jpg"
    },
    "3": {
      "name": "2 Euros University of Ljubljana",
      "price_cents": 1499,
      "country": "Slovenia",
      "year": 2019,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/003.jpg"
    },
    "4": {
      "name": "2 Euros Italian National Police",
      "price_cents": 1499,
      "country": "Italy",
      "year": 2022,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/004.jpg"
    },
    "5": {
      "name": "2 Euros Academy of Athens",
      "price_cents": 1499,
      "country": "Greece",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/005.jpg"
    },
    "6": {
      "name": "2 Euro Monastery of Poblet",
      "price_cents": 1499,
      "country": "Spain",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/006.jpg"
    },
    "7": {
      "name": "2 Euros Maria Callas",
      "price_cents": 1499,
      "country": "Greece",
      "year": 2023,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/007.jpg"
    },
    "8": {
      "name": "2 Euro Rotary",
      "price_cents": 1499,
      "country": "Portugal",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/008.jpg"
    },
    "9": {
      "name": "2 Euros First Flight from Malta",
      "price_cents": 1499,
      "country": "Malta",
      "year": 2015,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/009.jpg"
    },
    "10": {
      "name": "2 Euros Presidency European Union",
      "price_cents": 1499,
      "country": "Portugal",
      "year": 2021,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/010.jpg"
    },
    "11": {
      "name": "2 Euros Basketball in Lithuania",
      "price_cents": 1499,
      "country": "Lithuania",
      "year": 2022,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/011.jpg"
    },
    "12": {
      "name": "2 Euros Belgian Presidency of the Council of the EU",
      "price_cents": 1499,
      "country": "Belgium",
      "year": 2024,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/012.jpg"
    },
    "13": {
      "name": "2 Euros Primož Trubar",
      "price_cents": 1499,
      "country": "Slovenia",
      "year": 2008,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/013.jpg"
    },
    "14": {
      "name": "2 Euros Adam Bohorič",
      "price_cents": 1499,
      "country": "Slovenia",
      "year": 2020,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/014.jpg"
    },
    "15": {
      "name": "2 Euros Ljubljana Botanical Garden",
      "price_cents": 1499,
      "country": "Slovenia",
      "year": 2010,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/015.jpg"
    },
    "16": {
      "name": "2 Euros Energy Independence",
      "price_cents": 1499,
      "country": "Lithuania",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/016.jpg"
    },
    "17": {
      "name": "2 Euros Glory to Ukraine",
      "price_cents": 1499,
      "country": "Estonia",
      "year": 2022,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/017.jpg"
    },
    "18": {
      "name": "2 Euros Guimarães",
      "price_cents": 1499,
      "country": "Portugal",
      "year": 2012,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/018.jpg"
    },
    "19": {
      "name": "2 Euros Ivan Cankar",
      "price_cents": 1499,
      "country": "Slovenia",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/019.jpg"
    },
    "20": {
      "name": "2 Euros Provincial Museum for Carniola",
      "price_cents": 1499,
      "country": "Slovenia",
      "year": 2021,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/020.jpg"
    },
    "21": {
      "name": "2 Euros Erasmus Slovenia",
      "price_cents": 1499,
      "country": "Slovenia",
      "year": 2022,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/021.jpg"
    },
    "22": {
      "name": "2 Euros Marine Nationale 400ans",
      "price_cents": 1499,
      "country": "France",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/022.jpg"
    },
    "23": {
      "name": "2 Euros Visegrad Group",
      "price_cents": 1499,
      "country": "Slovakia",
      "year": 2011,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/023.jpg"
    },
    "24": {
      "name": "2 Euros Centaurea Cyanus",
      "price_cents": 1499,
      "country": "Estonia",
      "year": 2024,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/024.jpg"
    },
    "25": {
      "name": "2 Euros Raamat 500",
      "price_cents": 1499,
      "country": "Estonia",
      "year": 2025,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/025.jpg"
    },
    "26": {
      "name": "2 Euros 730 years of the University of Coimbra",
      "price_cents": 1499,
      "country": "Portugal",
      "year": 2020,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/026.jpg"
    },
    "27": {
      "name": "2 Euros Bundesländer II - \"Bremen\"",
      "price_cents": 1499,
      "country": "Germany",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/027.jpg"
    },
    "28": {
      "name": "2 Euros Constantin Caratheodory",
      "price_cents": 1499,
      "country": "Greece",
      "year": 2023,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/028.jpg"
    },
    "29": {
      "name": "2 Euros Joana Vasconcelos",
      "price_cents": 1499,
      "country": "Portugal",
      "year": 2016,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/029.jpg"
    },
    "30": {
      "name": "2 Euros Canis Lupus",
      "price_cents": 1499,
      "country": "Estonia",
      "year": 2021,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/030.jpg"
    },
    "31": {
      "name": "2 Euros Fernao Mendes Pinto",
      "price_cents": 1499,
      "country": "Portugal",
      "year": 2011,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/031.jpg"
    },
    "32": {
      "name": "2 Euros Majstrovstva Europy V Hokeji",
      "price_cents": 1499,
      "country": "Slovakia",
      "year": 2025,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/032.jpg"
    },
    "33": {
      "name": "2 Euros 10th Anniversary - Accession to the European Union",
      "price_cents": 1499,
      "country": "Slovakia",
      "year": 2014,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/033.jpg"
    },
    "34": {
      "name": "2 Euros 200th Anniversary - Exodus of Missolonghi",
      "price_cents": 1499,
      "country": "Greece",
      "year": 2026,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/034.jpg"
    },
    "35": {
      "name": "2 Euros Belgian Presidency of the Council of the European Union",
      "price_cents": 1499,
      "country": "Belgium",
      "year": 2010,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/035.jpg"
    },
    "36": {
      "name": "2 Euros 2500 years of the Battle of Thermopylae",
      "price_cents": 1499,
      "country": "Greece",
      "year": 2020,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/036.jpg"
    },
    "37": {
      "name": "2 Euros Erasmus Greece",
      "price_cents": 1499,
      "country": "Greece",
      "year": 2022,
      "colored": true,
      "image": "PRODUCT PHOTOS/COINS/037.jpg"
    },
    "38": {
      "name": "2 Euros Barbara of Celje",
      "country": "Slovenia",
      "year": 2014,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/001.png",
      "source_coin_id": 1,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Slovenia.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014.en.html",
      "image_frame": {
        "width": 104.152824,
        "height": 100.884956,
        "left": -2.159468,
        "top": -0.563154
      },
      "image_bounds": {
        "left": 26,
        "top": 7,
        "right": 1229,
        "bottom": 1249
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/001.jpg",
      "image_edit": "ai-retouched"
    },
    "40": {
      "name": "2 Euros University of Ljubljana",
      "country": "Slovenia",
      "year": 2019,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/003.png",
      "source_coin_id": 3,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2019/comm_2019_sv_100anni_university_ljublja.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2019.en.html",
      "image_frame": {
        "width": 100.884956,
        "height": 100.642055,
        "left": -0.241352,
        "top": 0
      },
      "image_bounds": {
        "left": 3,
        "top": 0,
        "right": 1245,
        "bottom": 1245
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/003.jpg",
      "image_edit": "ai-retouched"
    },
    "41": {
      "name": "2 Euros Italian National Police",
      "country": "Italy",
      "year": 2022,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/004.png",
      "source_coin_id": 4,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022/2022_1comm_Italy-polizia_540x540.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022.en.html",
      "image_frame": {
        "width": 101.785714,
        "height": 100.642055,
        "left": -0.487013,
        "top": 0
      },
      "image_bounds": {
        "left": 6,
        "top": 0,
        "right": 1237,
        "bottom": 1245
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/004.jpg",
      "image_edit": "ai-retouched"
    },
    "44": {
      "name": "2 Euros Maria Callas",
      "country": "Greece",
      "year": 2023,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/007.png",
      "source_coin_id": 7,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2023/IMG_0007.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2023.en.html",
      "image_frame": {
        "width": 102.786885,
        "height": 101.703163,
        "left": -1.065574,
        "top": -0.324412
      },
      "image_bounds": {
        "left": 13,
        "top": 4,
        "right": 1232,
        "bottom": 1236
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/007.jpg",
      "image_edit": "ai-retouched"
    },
    "46": {
      "name": "2 Euros First Flight from Malta",
      "country": "Malta",
      "year": 2015,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/009.png",
      "source_coin_id": 9,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2015/comm_2015_Malta.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2015.en.html",
      "image_frame": {
        "width": 104.239401,
        "height": 102.955665,
        "left": -1.745636,
        "top": -0.738916
      },
      "image_bounds": {
        "left": 21,
        "top": 9,
        "right": 1223,
        "bottom": 1226
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/009.jpg",
      "image_edit": "ai-retouched"
    },
    "47": {
      "name": "2 Euros Presidency European Union",
      "country": "Portugal",
      "year": 2021,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/010.png",
      "source_coin_id": 10,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2021/PT 2021 EU presidency.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2021.en.html",
      "image_frame": {
        "width": 101.047542,
        "height": 100.32,
        "left": -0.322321,
        "top": 0
      },
      "image_bounds": {
        "left": 4,
        "top": 0,
        "right": 1244,
        "bottom": 1249
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/010.jpg",
      "image_edit": "ai-retouched"
    },
    "48": {
      "name": "2 Euros Basketball in Lithuania",
      "country": "Lithuania",
      "year": 2022,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/011.png",
      "source_coin_id": 11,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022/0429-23r.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022.en.html",
      "image_frame": {
        "width": 103.465347,
        "height": 102.117264,
        "left": -1.485149,
        "top": -0.651466
      },
      "image_bounds": {
        "left": 18,
        "top": 8,
        "right": 1229,
        "bottom": 1235
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/011.jpg",
      "image_edit": "ai-retouched"
    },
    "49": {
      "name": "2 Euros Belgian Presidency of the Council of the EU",
      "country": "Belgium",
      "year": 2024,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/012.png",
      "source_coin_id": 12,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2024/2024_comm_Belgium2.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2024.en.html",
      "image_frame": {
        "width": 106.905371,
        "height": 106.451613,
        "left": -3.069054,
        "top": -2.801358
      },
      "image_bounds": {
        "left": 36,
        "top": 33,
        "right": 1208,
        "bottom": 1210
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/012.jpg",
      "image_edit": "ai-retouched"
    },
    "50": {
      "name": "2 Euros Primož Trubar",
      "country": "Slovenia",
      "year": 2008,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/013.png",
      "source_coin_id": 13,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Slovenia.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008.en.html",
      "image_frame": {
        "width": 102.702703,
        "height": 101.703163,
        "left": -0.819001,
        "top": -0.162206
      },
      "image_bounds": {
        "left": 10,
        "top": 2,
        "right": 1230,
        "bottom": 1234
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/013.jpg",
      "image_edit": "ai-retouched"
    },
    "51": {
      "name": "2 Euros Adam Bohorič",
      "country": "Slovenia",
      "year": 2020,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/014.png",
      "source_coin_id": 14,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2020/comm_2020_sl_birth_bohoric.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2020.en.html",
      "image_frame": {
        "width": 101.785714,
        "height": 101.620746,
        "left": -0.649351,
        "top": -0.567261
      },
      "image_bounds": {
        "left": 8,
        "top": 7,
        "right": 1239,
        "bottom": 1240
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/014.jpg",
      "image_edit": "ai-retouched"
    },
    "52": {
      "name": "2 Euros Ljubljana Botanical Garden",
      "country": "Slovenia",
      "year": 2010,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/015.png",
      "source_coin_id": 15,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2010/comm_2010_sl.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2010.en.html",
      "image_frame": {
        "width": 102.702703,
        "height": 101.210654,
        "left": -0.900901,
        "top": -0.322841
      },
      "image_bounds": {
        "left": 11,
        "top": 4,
        "right": 1231,
        "bottom": 1242
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/015.jpg",
      "image_edit": "ai-retouched"
    },
    "54": {
      "name": "2 Euros Glory to Ukraine",
      "country": "Estonia",
      "year": 2022,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/017.png",
      "source_coin_id": 17,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022/0424-23r.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022.en.html",
      "image_frame": {
        "width": 101.210654,
        "height": 101.292407,
        "left": -0.161421,
        "top": -0.323102
      },
      "image_bounds": {
        "left": 2,
        "top": 4,
        "right": 1240,
        "bottom": 1241
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/017.jpg",
      "image_edit": "ai-retouched"
    },
    "55": {
      "name": "2 Euros Guimarães",
      "country": "Portugal",
      "year": 2012,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/018.png",
      "source_coin_id": 18,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2012/comm_2012_pt.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2012.en.html",
      "image_frame": {
        "width": 102.955665,
        "height": 101.703163,
        "left": -1.067323,
        "top": -0.324412
      },
      "image_bounds": {
        "left": 13,
        "top": 4,
        "right": 1230,
        "bottom": 1236
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/018.jpg",
      "image_edit": "ai-retouched"
    },
    "57": {
      "name": "2 Euros Provincial Museum for Carniola",
      "country": "Slovenia",
      "year": 2021,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/020.png",
      "source_coin_id": 20,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2021/SL_Oct21.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2021.en.html",
      "image_frame": {
        "width": 103.294893,
        "height": 102.28385,
        "left": -1.317957,
        "top": -0.40783
      },
      "image_bounds": {
        "left": 16,
        "top": 5,
        "right": 1229,
        "bottom": 1230
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/020.jpg",
      "image_edit": "ai-retouched"
    },
    "58": {
      "name": "2 Euros Erasmus Slovenia",
      "country": "Slovenia",
      "year": 2022,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/021.png",
      "source_coin_id": 21,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022/Slovenia.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022.en.html",
      "image_frame": {
        "width": 102.702703,
        "height": 102.034174,
        "left": -0.982801,
        "top": -0.406835
      },
      "image_bounds": {
        "left": 12,
        "top": 5,
        "right": 1232,
        "bottom": 1233
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/021.jpg",
      "image_edit": "ai-retouched"
    },
    "59": {
      "name": "2 Euros Marine Nationale 400ans",
      "price_cents": 1499,
      "country": "France",
      "year": 2026,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/022.png",
      "source_coin_id": 22,
      "image_credit": "Monnaie de Paris",
      "image_source_url": "https://www.monnaiedeparis.fr/media/catalog/product/M/5/M5066_MDP_00070866_BD_ac41.jpg",
      "image_source_page": "https://www.monnaiedeparis.fr/en/french-navy-2eur-brilliant-uncirculated-commemorative-coin-brilliant-uncirculated-yeardate-2026",
      "image_frame": {
        "width": 104.674457,
        "height": 104.937238,
        "left": -2.086811,
        "top": -2.175732
      },
      "image_bounds": {
        "left": 25,
        "top": 26,
        "right": 1222,
        "bottom": 1220
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/022.jpg",
      "image_edit": "ai-retouched"
    },
    "60": {
      "name": "2 Euros Visegrad Group",
      "country": "Slovakia",
      "year": 2011,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/023.png",
      "source_coin_id": 23,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2011/comm_2011_sk.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2011.en.html",
      "image_frame": {
        "width": 103.893952,
        "height": 101.620746,
        "left": -1.491301,
        "top": -0.324149
      },
      "image_bounds": {
        "left": 18,
        "top": 4,
        "right": 1224,
        "bottom": 1237
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/023.jpg",
      "image_edit": "ai-retouched"
    },
    "61": {
      "name": "2 Euros Centaurea Cyanus",
      "country": "Estonia",
      "year": 2024,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/024.png",
      "source_coin_id": 24,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2024/IMG_0060.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2024.en.html",
      "image_frame": {
        "width": 103.465347,
        "height": 103.380049,
        "left": -0.990099,
        "top": -0.659522
      },
      "image_bounds": {
        "left": 12,
        "top": 8,
        "right": 1223,
        "bottom": 1220
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/024.jpg",
      "image_edit": "ai-retouched"
    },
    "62": {
      "name": "2 Euros Raamat 500",
      "country": "Estonia",
      "year": 2025,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/025.png",
      "source_coin_id": 25,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2025/Estonia_540x540.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2025.en.html",
      "image_frame": {
        "width": 103.722084,
        "height": 103.550784,
        "left": -1.406121,
        "top": -0.90834
      },
      "image_bounds": {
        "left": 17,
        "top": 11,
        "right": 1225,
        "bottom": 1221
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/025.jpg",
      "image_edit": "ai-retouched"
    },
    "63": {
      "name": "2 Euros 730 years of the University of Coimbra",
      "country": "Portugal",
      "year": 2020,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/026.png",
      "source_coin_id": 26,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2020/comm_2020_pt_university_coimbra.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2020.en.html",
      "image_frame": {
        "width": 100.480769,
        "height": 100.32,
        "left": -0.080128,
        "top": -0.08
      },
      "image_bounds": {
        "left": 1,
        "top": 1,
        "right": 1248,
        "bottom": 1250
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/026.jpg",
      "image_edit": "ai-retouched"
    },
    "64": {
      "name": "2 Euros Bundesländer II - \"Bremen\"",
      "price_cents": 1499,
      "country": "Germany",
      "year": 2026,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/027.png",
      "source_coin_id": 27,
      "image_credit": "Münze Deutschland",
      "image_source_url": "https://muenze-deutschland.de/out/pictures/generated/product/1/1200_1200_85/2_euro_bremen_2026_bs_1300x1272(2).png",
      "image_source_page": "https://muenze-deutschland.de/Muenzen/2-Euro-Sammlermuenzen-Set/2-Euro-Sammlermuenzen-Set-2026-Bundeslaender-II.html",
      "image_frame": {
        "width": 103.807947,
        "height": 105.733558,
        "left": -0.57947,
        "top": -1.517707
      },
      "image_bounds": {
        "left": 7,
        "top": 18,
        "right": 1214,
        "bottom": 1203
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/027.png",
      "image_edit": "ai-retouched"
    },
    "65": {
      "name": "2 Euros Constantin Caratheodory",
      "country": "Greece",
      "year": 2023,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/028.png",
      "source_coin_id": 28,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2023/IMG_0023_540x540.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2023.en.html",
      "image_frame": {
        "width": 104.239401,
        "height": 102.367347,
        "left": -1.745636,
        "top": 0
      },
      "image_bounds": {
        "left": 21,
        "top": 0,
        "right": 1223,
        "bottom": 1224
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/028.jpg",
      "image_edit": "ai-retouched"
    },
    "66": {
      "name": "2 Euros Joana Vasconcelos",
      "country": "Portugal",
      "year": 2016,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/029.png",
      "source_coin_id": 29,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2016/comm_2016_portugal_olympics_270.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2016.en.html",
      "image_frame": {
        "width": 103.9801,
        "height": 101.8684,
        "left": -1.824212,
        "top": -0.487409
      },
      "image_bounds": {
        "left": 22,
        "top": 6,
        "right": 1227,
        "bottom": 1236
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/029.jpg",
      "image_edit": "ai-retouched"
    },
    "67": {
      "name": "2 Euros Canis Lupus",
      "country": "Estonia",
      "year": 2021,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/030.png",
      "source_coin_id": 30,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2021/comm_2021_estonia-wolf.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2021.en.html",
      "image_frame": {
        "width": 102.200489,
        "height": 101.292407,
        "left": -0.651997,
        "top": -0.242326
      },
      "image_bounds": {
        "left": 8,
        "top": 3,
        "right": 1234,
        "bottom": 1240
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/030.jpg",
      "image_edit": "ai-retouched"
    },
    "68": {
      "name": "2 Euros Fernao Mendes Pinto",
      "country": "Portugal",
      "year": 2011,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/031.png",
      "source_coin_id": 31,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2011/comm_2011_pt.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2011.en.html",
      "image_frame": {
        "width": 102.871206,
        "height": 101.785714,
        "left": -0.902379,
        "top": -0.487013
      },
      "image_bounds": {
        "left": 11,
        "top": 6,
        "right": 1229,
        "bottom": 1237
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/031.jpg",
      "image_edit": "ai-retouched"
    },
    "69": {
      "name": "2 Euros Majstrovstva Europy V Hokeji",
      "country": "Slovakia",
      "year": 2025,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/032.png",
      "source_coin_id": 32,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2025/Slovakia.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2025.en.html",
      "image_frame": {
        "width": 103.294893,
        "height": 103.550784,
        "left": -1.400329,
        "top": -1.486375
      },
      "image_bounds": {
        "left": 17,
        "top": 18,
        "right": 1230,
        "bottom": 1228
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/032.jpg",
      "image_edit": "ai-retouched"
    },
    "70": {
      "name": "2 Euros 10th Anniversary - Accession to the European Union",
      "country": "Slovakia",
      "year": 2014,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/033.png",
      "source_coin_id": 33,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Slovakia.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014.en.html",
      "image_frame": {
        "width": 103.040263,
        "height": 102.117264,
        "left": -0.986031,
        "top": -0.325733
      },
      "image_bounds": {
        "left": 12,
        "top": 4,
        "right": 1228,
        "bottom": 1231
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/033.jpg",
      "image_edit": "ai-retouched"
    },
    "72": {
      "name": "2 Euros Belgian Presidency of the Council of the European Union",
      "country": "Belgium",
      "year": 2010,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/035.png",
      "source_coin_id": 35,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2010/comm_2010_be.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2010.en.html",
      "image_frame": {
        "width": 103.722084,
        "height": 101.95122,
        "left": -1.406121,
        "top": -0.406504
      },
      "image_bounds": {
        "left": 17,
        "top": 5,
        "right": 1225,
        "bottom": 1234
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/035.jpg",
      "image_edit": "ai-retouched"
    },
    "73": {
      "name": "2 Euros 2500 years of the Battle of Thermopylae",
      "country": "Greece",
      "year": 2020,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/036.png",
      "source_coin_id": 36,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2020/comm_2020_gr_battle_thermopylae.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2020.en.html",
      "image_frame": {
        "width": 101.210654,
        "height": 100.722892,
        "left": -0.403551,
        "top": 0
      },
      "image_bounds": {
        "left": 5,
        "top": 0,
        "right": 1243,
        "bottom": 1244
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/036.jpg",
      "image_edit": "ai-retouched"
    },
    "74": {
      "name": "2 Euros Erasmus Greece",
      "country": "Greece",
      "year": 2022,
      "colored": false,
      "image": "PRODUCT PHOTOS/COINS/RETOUCHED/037.png",
      "source_coin_id": 37,
      "price_cents": 1499,
      "image_source_url": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022/Greece.jpg",
      "image_source_page": "https://www.ecb.europa.eu/euro/coins/comm/html/comm_2022.en.html",
      "image_frame": {
        "width": 103.040263,
        "height": 102.45098,
        "left": -0.986031,
        "top": -0.653595
      },
      "image_bounds": {
        "left": 12,
        "top": 8,
        "right": 1228,
        "bottom": 1231
      },
      "image_quality_review": "approved_clean_finish_ai_illustration",
      "image_original": "PRODUCT PHOTOS/COINS/UNCOLORED/037.jpg",
      "image_edit": "ai-retouched"
    }
  },
  "coin_image_reference": {
    "width": 92.125,
    "height": 93.4375,
    "center_x": 50.25,
    "center_y": 49.65625,
    "source_coin_id": 1,
    "face": {
      "width": 92.125,
      "height": 93.4375,
      "left": 4.1875,
      "top": 2.9375
    }
  }
};

type Product = { name: string; price_cents: number; colored?: boolean };
const PRODUCTS: Record<string, Product> = priceCatalog.products;
const SHIPPING_CENTS = priceCatalog.shipping_cents;

type Dependencies = {
  env: (name: string) => string | undefined;
  createSupabaseClient: typeof createClient;
  createStripeClient: (secret: string) => Pick<Stripe, "checkout">;
};

function jsonResponse(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function getSupabasePublicKey(env: Dependencies["env"]): string | null {
  const legacyKey = env("SUPABASE_ANON_KEY");
  if (legacyKey) return legacyKey;
  const publishableKeys = env("SUPABASE_PUBLISHABLE_KEYS");
  if (!publishableKeys) return null;
  try {
    const parsed = JSON.parse(publishableKeys);
    const key = parsed.default || Object.values(parsed)[0];
    return typeof key === "string" && key ? key : null;
  } catch { return null; }
}

export function createCheckoutHandler(deps: Dependencies) {
  return async (req: Request): Promise<Response> => {
    if (req.method === "OPTIONS") {
      return new Response("ok", { status: 200, headers: corsHeaders });
    }
    if (req.method !== "POST") return jsonResponse({ error: "Method not allowed" }, 405);
    try {
      const authHeader = req.headers.get("Authorization");
      if (!authHeader) return jsonResponse({ error: "You must be logged in" }, 401);
      const stripeSecret = deps.env("STRIPE_SECRET_KEY");
      const supabaseUrl = deps.env("SUPABASE_URL");
      const supabaseKey = getSupabasePublicKey(deps.env);
      if (!stripeSecret) return jsonResponse({ error: "Stripe secret key is missing" }, 500);
      if (!supabaseUrl || !supabaseKey) return jsonResponse({ error: "Supabase configuration is missing" }, 500);
      const supabase = deps.createSupabaseClient(supabaseUrl, supabaseKey, {
        global: { headers: { Authorization: authHeader } },
        auth: { persistSession: false, autoRefreshToken: false },
      });
      const { data: { user }, error: userError } = await supabase.auth.getUser();
      if (userError || !user) return jsonResponse({ error: "Invalid user session" }, 401);
      const { data: cart, error: cartError } = await supabase.from("cart")
        .select("coin_id, quantity").eq("user_id", user.id);
      if (cartError) return jsonResponse({ error: "Could not load cart" }, 500);
      if (!cart?.length) return jsonResponse({ error: "Your cart is empty" }, 400);
      const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] = [];
      for (const item of cart) {
        const coinId = Number(item.coin_id);
        const quantity = Number(item.quantity);
        if (!Number.isSafeInteger(coinId) || coinId < 1) return jsonResponse({ error: "Invalid coin ID" }, 400);
        const product = PRODUCTS[coinId];
        if (!product) return jsonResponse({ error: `Unknown coin ID: ${coinId}` }, 400);
        if (!Number.isSafeInteger(quantity) || quantity < 1 || quantity > 100) {
          return jsonResponse({ error: `Invalid quantity for coin ${coinId}` }, 400);
        }
        if (!Number.isSafeInteger(product.price_cents) || product.price_cents < 0) {
          throw new Error(`Invalid price configuration for coin ${coinId}`);
        }
        // Always use the server's catalogue; request-body prices are ignored.
        lineItems.push({ quantity, price_data: {
          currency: "eur", unit_amount: product.price_cents,
          product_data: { name: product.colored === false ? `${product.name} (Uncoloured)` : product.name },
        } });
      }
      if (!Number.isSafeInteger(SHIPPING_CENTS) || SHIPPING_CENTS < 0) {
        throw new Error("Invalid shipping price configuration");
      }
      const stripe = deps.createStripeClient(stripeSecret);
      const session = await stripe.checkout.sessions.create({
        mode: "payment", line_items: lineItems,
        shipping_address_collection: { allowed_countries: [
          "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU",
          "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE",
        ] },
        shipping_options: [{ shipping_rate_data: {
          type: "fixed_amount", fixed_amount: { amount: SHIPPING_CENTS, currency: "eur" },
          display_name: "EU Shipping",
        } }],
        phone_number_collection: { enabled: true },
        customer_email: user.email ?? undefined,
        client_reference_id: user.id, metadata: { user_id: user.id },
        success_url: "https://arkianscollectibles.com/success.html?session_id={CHECKOUT_SESSION_ID}",
        cancel_url: "https://arkianscollectibles.com/cart.html",
      });
      if (!session.url) return jsonResponse({ error: "Stripe checkout URL was not returned" }, 500);
      return jsonResponse({ url: session.url });
    } catch (error) {
      console.error("Checkout error:", error);
      return jsonResponse({ error: "Checkout failed" }, 500);
    }
  };
}

Deno.serve(createCheckoutHandler({
  env: (name) => Deno.env.get(name),
  createSupabaseClient: createClient,
  createStripeClient: (secret) => new Stripe(secret),
}));
