import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
const source = new URL('../supabase/functions/_shared/product-prices.json', import.meta.url);
const target = new URL('../product-prices.js', import.meta.url);
const catalog = JSON.parse(readFileSync(source, 'utf8'));
if (!Number.isSafeInteger(catalog.shipping_cents) || catalog.shipping_cents < 0) throw Error('Invalid shipping_cents');
if (!catalog.products || !Object.keys(catalog.products).length) throw Error('Empty product catalogue');
for (const [id, product] of Object.entries(catalog.products)) {
  if (!/^\d+$/.test(id) || Number(id) < 1 || !Number.isSafeInteger(Number(id))) throw Error(`Invalid product ID: ${id}`);
  if (!product.name || !Number.isSafeInteger(product.price_cents) || product.price_cents < 0) throw Error(`Invalid product: ${id}`);
}
const output = '// Generated by node scripts/build-prices.mjs. Edit supabase/functions/_shared/product-prices.json.\n'
  + 'globalThis.ARKIANS_PRICES = ' + JSON.stringify(catalog, null, 2) + ';\n';
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== output) throw Error('product-prices.js is stale; run node scripts/build-prices.mjs');
} else writeFileSync(target, output);

// A standalone copy for the Dashboard editor, generated from the same source.
const handler = readFileSync(new URL('../supabase/functions/create-checkout-function/checkout.ts', import.meta.url), 'utf8')
  .replace('import type Stripe', 'import Stripe')
  .replace('import type { createClient }', 'import { createClient }')
  .replace('import priceCatalog from "../_shared/product-prices.json" with { type: "json" };',
    'const priceCatalog = ' + JSON.stringify(catalog, null, 2) + ';');
const standalone = '// Generated by node scripts/build-prices.mjs. Do not edit this copy.\n' + handler
  + '\nDeno.serve(createCheckoutHandler({\n  env: (name) => Deno.env.get(name),\n  createSupabaseClient: createClient,\n  createStripeClient: (secret) => new Stripe(secret),\n}));\n';
const dashboardFile = new URL('../supabase/dashboard/create-checkout-function.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(dashboardFile, 'utf8') !== standalone) throw Error('Dashboard function is stale; run node scripts/build-prices.mjs');
} else writeFileSync(dashboardFile, standalone);

// Invalidate website price caches whenever the shared catalogue changes.
const cacheTag = createHash('sha256').update(JSON.stringify(catalog)).digest('hex').slice(0, 12);
for (const filename of readdirSync(new URL('../', import.meta.url)).filter(name => name.endsWith('.html'))) {
  const file = new URL('../' + filename, import.meta.url);
  const current = readFileSync(file, 'utf8');
  const updated = current.replace(/product-prices\.js\?v=[^"\s]+/g, 'product-prices.js?v=' + cacheTag);
  if (process.argv.includes('--check')) {
    if (current !== updated) throw Error(`Stale price cache tag in ${filename}; run node scripts/build-prices.mjs`);
  } else if (current !== updated) writeFileSync(file, updated);
}
